[Appearance]
custom_palette=false
icon_theme=Papirus-Dark
standard_dialogs=default
style=kvantum

[Fonts]
# leave Qt's defaults; set here if you ever want a specific UI font

[Interface]
double_click_interval=400
cursor_flash_time=1000
buttonbox_layout=0
keyboard_scheme=2
gui_effects=@Invalid()
stylesheets=@Invalid()
toolbutton_style=4
activate_item_on_single_click=1
underline_shortcut=1
show_shortcuts_in_context_menus=1

[SettingsWindow]
geometry=@Invalid()

[Troubleshooting]
force_raster_widgets=1
ignored_applications=@Invalid()
